from dataclasses import dataclass, field
from typing import Optional
from datetime import datetime


@dataclass
class SlackCommand:
    """Parsed Slack slash command data."""
    topic: str
    audience: str
    goal: str
    template_id: str
    response_url: str
    user_id: str
    user_name: str
    channel_id: str

    @classmethod
    def from_slack_body(cls, body: dict) -> "SlackCommand":
        """Parse Slack webhook body into command."""
        text = body.get("text", "").strip()
        parts = text.split() if text else []

        return cls(
            topic=parts[0] if len(parts) > 0 else "general campaign",
            audience=parts[1] if len(parts) > 1 else "customers",
            goal=parts[2] if len(parts) > 2 else "engagement",
            template_id=parts[3] if len(parts) > 3 else "314854693604",
            response_url=body.get("response_url", ""),
            user_id=body.get("user_id", ""),
            user_name=body.get("user_name", ""),
            channel_id=body.get("channel_id", ""),
        )


@dataclass
class BrandContext:
    """Brand context extracted from documents."""
    voice_tone: str = ""
    positioning: str = ""
    target_audience: str = ""
    example_copy: str = ""
    files_processed: list[str] = field(default_factory=list)

    def is_empty(self) -> bool:
        return not any([
            self.voice_tone,
            self.positioning,
            self.target_audience,
            self.example_copy,
        ])


@dataclass
class EmailVariation:
    """Single email variation generated by AI."""
    approach: str  # benefit-focused, story-driven, urgency-based
    subject: str
    preview: str
    body_html: str
    cta_text: str


@dataclass
class GenerationRequest:
    """Full generation request with context."""
    command: SlackCommand
    brand_context: BrandContext
    timestamp: datetime = field(default_factory=datetime.utcnow)


@dataclass
class HubSpotDraft:
    """Created HubSpot email draft."""
    email_id: str
    draft_url: str
    approach: str
    subject: str


@dataclass
class GenerationResult:
    """Complete result of a generation run."""
    request: GenerationRequest
    variations: list[EmailVariation]
    drafts: list[HubSpotDraft]
    duration_seconds: float
    errors: list[str] = field(default_factory=list)
