# models/schemas.py
# Data classes used throughout the application.
# Using dataclasses for lightweight type safety without a heavy ORM dependency.

from dataclasses import dataclass, field
from typing import Optional
from datetime import datetime


@dataclass
class SlackCommand:
    """Parsed Slack slash command data."""

    topic: str
    audience: str
    goal: str
    template_id: Optional[str]  # None means use config default
    response_url: str
    user_id: str
    user_name: str
    channel_id: str

    @classmethod
    def from_slack_body(cls, body: dict) -> "SlackCommand":
        """Parse Slack webhook body into a typed command.

        Expected format: /campaign <topic> <audience> <goal> [template_id]
        The template_id is optional — if omitted, config default is used.
        """
        text = body.get("text", "").strip()
        parts = text.split() if text else []

        return cls(
            topic=parts[0] if len(parts) > 0 else "general campaign",
            audience=parts[1] if len(parts) > 1 else "customers",
            goal=parts[2] if len(parts) > 2 else "engagement",
            template_id=parts[3] if len(parts) > 3 else None,
            response_url=body.get("response_url", ""),
            user_id=body.get("user_id", ""),
            user_name=body.get("user_name", ""),
            channel_id=body.get("channel_id", ""),
        )


@dataclass
class BrandContext:
    """Brand context extracted from Google Drive documents.

    Files are categorized by filename keywords into the appropriate fields,
    then injected into the Claude prompt as structured sections.
    """

    voice_tone: str = ""
    positioning: str = ""
    target_audience: str = ""
    example_copy: str = ""
    files_processed: list[str] = field(default_factory=list)

    def is_empty(self) -> bool:
        """Returns True if no brand context was loaded."""
        return not any([
            self.voice_tone,
            self.positioning,
            self.target_audience,
            self.example_copy,
        ])


@dataclass
class EmailVariation:
    """Single email variation generated by Claude."""

    approach: str   # benefit-focused | story-driven | urgency-based
    subject: str
    preview: str
    body_html: str
    cta_text: str


@dataclass
class GenerationRequest:
    """Full generation request with context, for logging."""

    command: SlackCommand
    brand_context: BrandContext
    timestamp: datetime = field(default_factory=datetime.utcnow)


@dataclass
class HubSpotDraft:
    """A created HubSpot email draft ready for editing."""

    email_id: str
    draft_url: str
    approach: str
    subject: str


@dataclass
class GenerationResult:
    """Complete result of a single generation run."""

    request: GenerationRequest
    variations: list[EmailVariation]
    drafts: list[HubSpotDraft]
    duration_seconds: float
    errors: list[str] = field(default_factory=list)
